### ISSUE TITLE
爬取淘宝商品详情出现了以下错误

### ISSUE THREAD

**Issue by Ccccccai777** [youngzm339/taobao-crawler-selenium#3]
taobao-crawler-selenium-master>python taobaoCrawler.py
using new version selector
Traceback (most recent call last):
  File "taobaoCrawler.py", line 152, in <module>
    next_page_button.click()
  File "E:\python3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "E:\python3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "E:\python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "E:\python3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="下一页，当前第1页" type="button" class="next-btn next-small next-btn-normal next-pagination-item next-next">...</button> is not clickable at point (1085, 12). Other element would receive the click: <div class="PageHeader--innerWrap--u6MMclq" style="padding: 7px 16px; min-width: 1296px; justify-content: center;">...</div>
  (Session info: chrome=124.0.6367.119)

**Comment by Ccccccai777** [comment]
解决这个问题后导出的excel是空数据

**Comment by YoungZM339** [comment]
您好，现在淘宝网页版开始大改版，这个程序是去年夏天时编写，已经不适合现在的淘宝网页版。
近期我会更新这个程序，请您持续关注。

**Comment by zc9** [comment]
> 您好，现在淘宝网页版开始大改版，这个程序是去年夏天时编写，已经不适合现在的淘宝网页版。 近期我会更新这个程序，请您持续关注。

淘宝图像验证码能处理吗
